version: '3'

volumes:

  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:

  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data

  backend:
    image: hopedforluck/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/backend_media

  frontend:
    image: hopedforluck/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    env_file: .env
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/staticfiles/
      - media_foodgram:/media/

    ports:
      - "8000:80"
