version: '3'

volumes:

  pg_data_fg:
  static_fg:
  media_fg:
  frontend_fg:
  docs_fg:

services:

  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_fg:/var/lib/postgresql/data

  backend:
    image: hopedforluck/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static_fg:/app/static/
      - media_fg:/app/media/

  frontend:
    image: hopedforluck/foodgram_frontend
    volumes:
      - frontend_fg:/app/result_build/

  nginx:
    image: nginx:1.19.3
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_fg:/usr/share/nginx/html/
      - docs_fg:/usr/share/nginx/html/api/docs/
      - static_fg:/var/html/static/
      - media_fg:/var/html/media/
    depends_on:
      - db
      - backend
      - frontend

    ports:
      - "8000:80"