version: '3'

volumes:

  pg_data_fg:
  static_fg:
  media_fg:

services:

  db:
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_fg:/var/lib/postgresql/data

  backend:
    image: hopedforluck/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static_fg:/backend_static
      - media_fg:/backend_media

  frontend:
    image: hopedforluck/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    env_file: .env
    restart: always
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_fg:/staticfiles/
      - media_fg:/media/

    ports:
      - "8000:80"
